CHANGELOG.md, lib/config.js, lib/webpay.js, package-lock.json, package.json
Prepare release 1.0.3 
[Full diff](https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/1.0.2...chore/prepare-release-1.0.3)
=> Chore/prepare release 1.0.3

.travis.yml, CHANGELOG.md, package.json
=> Chore/prepare release 2.0.0

lib/index.ts, lib/transbank/webpay/common/transaction_detail.ts, lib/transbank/webpay/oneclick/index.ts, lib/transbank/webpay/oneclick/mall_deferred_inscription.ts, lib/transbank/webpay/oneclick/mall_deferred_transaction.ts, lib/transbank/webpay/oneclick/mall_inscription.ts, lib/transbank/webpay/oneclick/mall_transaction.ts, lib/transbank/webpay/oneclick/requests/authorize_request.ts, lib/transbank/webpay/oneclick/requests/capture_request.ts, lib/transbank/webpay/oneclick/requests/delete_request.ts, lib/transbank/webpay/oneclick/requests/finish_request.ts, lib/transbank/webpay/oneclick/requests/index.ts, lib/transbank/webpay/oneclick/requests/refund_request.ts, lib/transbank/webpay/oneclick/requests/start_request.ts, lib/transbank/webpay/oneclick/requests/status_request.ts
This add OneClick Mall and OneClick Mall Deferred
=> Add Oneclick Mall and Oneclick Mall Deferred

lib/index.ts, lib/transbank/webpay/common/installments_detail.ts, lib/transbank/webpay/transaccion_completa/common/commit_detail.ts, lib/transbank/webpay/transaccion_completa/deferred_transaction.ts, lib/transbank/webpay/transaccion_completa/index.ts, lib/transbank/webpay/transaccion_completa/mall_deferred_transaction.ts, lib/transbank/webpay/transaccion_completa/mall_transaction.ts, lib/transbank/webpay/transaccion_completa/requests/capture_request.ts, lib/transbank/webpay/transaccion_completa/requests/commit_request.ts, lib/transbank/webpay/transaccion_completa/requests/create_request.ts, lib/transbank/webpay/transaccion_completa/requests/index.ts, lib/transbank/webpay/transaccion_completa/requests/installments_request.ts, lib/transbank/webpay/transaccion_completa/requests/mall_capture_request.ts, lib/transbank/webpay/transaccion_completa/requests/mall_commit_request.ts, lib/transbank/webpay/transaccion_completa/requests/mall_create_request.ts, lib/transbank/webpay/transaccion_completa/requests/mall_refund_request.ts, lib/transbank/webpay/transaccion_completa/requests/refund_request.ts, lib/transbank/webpay/transaccion_completa/requests/status_request.ts, lib/transbank/webpay/transaccion_completa/transaction.ts
This adds Transacción Completa REST
=> Add Transacción Completa REST

lib/transbank/webpay/common/transaction_detail.ts, lib/transbank/webpay/oneclick/index.ts, lib/transbank/webpay/webpay_plus/index.ts
Fix type of transaction Classe so IDEs can pick it up correctly
=> Add transaction types in product modules

lib/transbank/webpay/common/transaction_detail.ts
Fix Transaction Detail Installments Number data type and remove if
=> Fix Transaction Detail Installments Number data type and remove if

.travis.yml, CHANGELOG.md, package.json
Full diff here: https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/2.0.0...master
=> Prepare release 2.1.0

.travis.yml
Change travis API Key to automation and add some minor configurations
=> Change travis Api Key

lib/transbank/common/request_service.ts, lib/transbank/webpay/oneclick/requests/delete_request.ts
Inscription delete was not working properly
=> Fix Oneclick inscription delete

.travis.yml, CHANGELOG.md, package-lock.json, package.json
Full diff https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/2.1.0...chore/prepare-release-2.1.1
=> Prepare release 2.1.1

.travis.yml
=> Fix travis cleanup

CHANGELOG.md, package.json
Full diff https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/2.1.1...chore/prepare-release-2.1.2
=> Prepare release 2.1.2

lib/transbank/webpay/webpay_plus/index.ts
Add missing configuration method in Webpay Plus module
=> Add webpay config methods

lib/transbank/webpay/oneclick/index.ts, lib/transbank/webpay/transaccion_completa/index.ts, lib/transbank/webpay/webpay_plus/index.ts, package-lock.json
Transaction objects were changeable variables, that shouldn't be
=> Change all Transaction objects to constants

lib/transbank/webpay/transaccion_completa/deferred_transaction.ts
it said sessionId when it should have been authorization code
=> Fix Transacción Completa capture param name

CHANGELOG.md, package-lock.json, package.json
Full diff https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/2.1.2...master
=> Prepare release 2.1.3

CHANGELOG.md, package.json
Full diff https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/2.1.3...master
=> add 3.0.0 changelog

CHANGELOG.md, package.json
Full diff
https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/3.0.0...master
=> add 3.0.1 changelog

CHANGELOG.md, package.json
=> Prepare Release 3.0.2

CHANGELOG.md, package.json
Full diff: https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/3.0.2...master
=> add 4.0.0 changelog

CHANGELOG.md, package.json
- Se actualiza certificado Público de Transbank
- Se evita la ejecución de test deprecados
Full diff : https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/1.0.3...1.x
=> add 1.0.4 changelog

.github/workflows/build.yml, sonar-project.properties
Implementing files to configure sonarcloud
=> chore: sonarcloud implementation

README.md
* add instructions for tagging a version as the latest
=> add instructions for tagging a version as the latest

jest.config.js
This pull request makes changes to the config.js file to address a recommendation provided by Kiuwan.
=> fix: .config.js for kiuwan report

.github/workflows/build.yml, CHANGELOG.md, jest.config.js, package-lock.json, package.json
Full diff: https://github.com/TransbankDevelopers/transbank-sdk-nodejs/compare/master...chore/prepare-release-5.0.0
=> Prepare Release 5.0.0

tests/common/options.test.ts, tests/mocks/oneclick_data.ts, tests/mocks/transaccion_completa_data.ts, tests/mocks/webpay_data.ts, tests/patpass/inscription.test.ts, tests/webpay/oneclick/mall_transaction.test.ts, tests/webpay/transaccion_completa/mall_transaction.test.ts, tests/webpay/transaccion_completa/mall_transaction_2.test.ts, tests/webpay/transaccion_completa/transaction.test.ts, tests/webpay/webpay_plus/mall_transaction.test.ts, tests/webpay/webpay_plus/mall_transaction_2.test.ts, tests/webpay/webpay_plus/transaction.test.ts
this PR:
* refactored by kiuwan's request
* kiuwan alerts fixed
=> refactor: kiuwan alerts

package-lock.json, package.json
This PR:
* update axios to 1.7.9
* update dev libraries
=> chore: update libraries

.github/workflows/npm_package.yml
change cache action version from 2 to 3
=> chore: update cache action version

.github/workflows/build.yml, package.json, sonar-project.properties
This PR update build workflow to add coverage report
=> chore: add coverage report

lib/transbank/webpay/oneclick/index.ts, lib/transbank/webpay/oneclick/mall_bin_info.ts, lib/transbank/webpay/oneclick/requests/index.ts, lib/transbank/webpay/oneclick/requests/query_bin_request.ts, tests/webpay/oneclick/mall_bin_info.test.ts
This PR add class to get BIN information.
=> feat: add info bin

lib/transbank/common/request_service.ts, lib/transbank/webpay/common/installments_detail.ts, lib/transbank/webpay/common/transaction_detail.ts, lib/transbank/webpay/oneclick/requests/authorize_request.ts, lib/transbank/webpay/oneclick/requests/capture_request.ts, lib/transbank/webpay/oneclick/requests/delete_request.ts, lib/transbank/webpay/oneclick/requests/query_bin_request.ts, lib/transbank/webpay/oneclick/requests/refund_request.ts, lib/transbank/webpay/oneclick/requests/start_request.ts, lib/transbank/webpay/transaccion_completa/common/commit_detail.ts, lib/transbank/webpay/transaccion_completa/mall_transaction.ts, lib/transbank/webpay/transaccion_completa/requests/capture_request.ts, lib/transbank/webpay/transaccion_completa/requests/commit_request.ts, lib/transbank/webpay/transaccion_completa/requests/create_request.ts, lib/transbank/webpay/transaccion_completa/requests/installments_request.ts, lib/transbank/webpay/transaccion_completa/requests/mall_commit_request.ts, lib/transbank/webpay/transaccion_completa/requests/mall_create_request.ts, lib/transbank/webpay/transaccion_completa/requests/mall_refund_request.ts, lib/transbank/webpay/webpay_plus/requests/capture_request.ts, lib/transbank/webpay/webpay_plus/requests/create_request.ts, lib/transbank/webpay/webpay_plus/requests/mall_capture_request.ts, lib/transbank/webpay/webpay_plus/requests/mall_create_request.ts, lib/transbank/webpay/webpay_plus/requests/mall_refund_request.ts
This PR add changes recommended by kiuwan
=> refactor: kiwan report

.github/workflows/build.yml, tests/webpay/oneclick/mall_bin_info.test.ts
This PR add changes recommended by kiuwan
=> refactor: kiuwan report

.github/workflows/build.yml, CHANGELOG.md, package-lock.json, package.json, tests/webpay/oneclick/mall_bin_info.test.ts
PR for release of version 6.1.1
This release includes:
- Update outdated dependencies
=> release: prepare release 6.1.1
